language: cpp
compiler:
  - clang
  - gcc
before_install:
 - sudo apt-get update
 - sudo apt-get install libgtest-dev libboost-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
script: "make test"
notifications:
  recipients:
    - alessandro.pezzato@gmail.com
  email:
    on_success: change
    on_failure: change
